### ISSUE TITLE
Support for tags, categories and archives ?

### ISSUE THREAD

**Issue by minima1cha0s** [gfjaru/Kiko#5]
Is it possible to implement tags, categories and archives with this ?

**Comment by gfjaru** [comment]
Its possible, you just add some code to layouts files.

But i cant do that, this theme just for personal blog. No categories, tags, and archives.

No archives ? Because all post will be shown at index.html

**Comment by minima1cha0s** [comment]
Yep done it here : pointless.surge.sh
Thank You, it is a great theme. I love it...
