### ISSUE TITLE
Formatting screwed up

### ISSUE THREAD

**Issue by DilankaW** [gfjaru/Kiko#6]
![screen shot 2015-12-28 at 3 36 16 pm](https://cloud.githubusercontent.com/assets/1406947/12027281/de115904-ad78-11e5-938a-4a7878dd32b2.png)
![screen shot 2015-12-28 at 3 35 48 pm](https://cloud.githubusercontent.com/assets/1406947/12027282/de122bfe-ad78-11e5-9afc-ac0dc2904929.png)
![screen shot 2015-12-28 at 3 30 30 pm](https://cloud.githubusercontent.com/assets/1406947/12027280/de0f1fd6-ad78-11e5-8a22-e0026e65d427.png)

Great theme. Except when I drag and drop my posts from my old Jekyll, they are broken. Especially the code segments. (Which are inclosed in {% highlight c %} .... { endhighlight } tags.

How do I fix this? 

Also, having a long string enclosed in `......` seems to make this theme NOT responsive. It trails off...

**Comment by gfjaru** [comment]
Can i see your markdown file ?

```
{% highlight c %}

// Your code here

{% endhighlight %}
```
